version: '3.7'
services:
  nodejs-api:
    build:
      context: ./
    ports:
      - '3000:3000'
    container_name: mongo-db
  mongo-db:
    image: mongo
    ports:
      - '27017:27017'
    container_name: mongo-db
    volumes:
      - ./db/:/data/db
