POST http://localhost:4000/auth/signUp
Content-Type: application/json

{
  "name": "user-nuevo",
  "email": "user-nuevo1@gmail.com",
  "password": "12345678",
  "role": "USER"
}
### login

POST http://localhost:4000/auth/login
Content-Type: application/json

{
  "email": "user-nuevo1@gmail.com",
  "password": "12345678"
}
### get logged in current user profile info

GET http://localhost:4000/auth/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZmFjMjc4NTRhNGQyZTM2YThjNTBkNCIsImlhdCI6MTY0MzgyMzc2NiwiZXhwIjoxNjQzOTEwMTY2fQ._USgmhRK_wk8m_m6aKiZ7YrCmW8jfxeHPVLZmZUd_6U


# ### logout
# POST http://localhost:4000/auth/logout
# Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZmFjMjc4NTRhNGQyZTM2YThjNTBkNCIsImlhdCI6MTY0MzgyMzc2NiwiZXhwIjoxNjQzOTEwMTY2fQ._USgmhRK_wk8m_m6aKiZ7YrCmW8jfxeHPVLZmZUd_6U


###

POST http://localhost:4000/auth/login
Content-Type: application/json

{
  "email": "parkcarlosseb@gmail.com",
  "password": "123456789"
}


### RESPONSE
# {
#   "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZWVhMjI1NmUwZGNmOGM1YWJmNzI5YiIsImlhdCI6MTY0MzA2NTg0NSwiZXhwIjoxNjQzMTUyMjQ1fQ.xUXTscSrAzvswNTwwFbBa3CaPRwN_0njQkUzrP08gO0"
# }

POST http://localhost:4000/hotels
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZWVhMjI1NmUwZGNmOGM1YWJmNzI5YiIsImlhdCI6MTY0MzI5MjQ0MywiZXhwIjoxNjQzMzc4ODQzfQ.ovFSIKnzGxCQnVCqKJS_49MnLiY1F1_yWScFOohbJjU
Content-Type: application/json

{
  "name": "Hotel 3",
  "description": "hotel 3 description",
  "email": "hotel-falso3@gmail.com",
  "address": "123 Fake St",
  "category": "TWO_START", 
  "price": 1250000
}

### RESPONSE
# {
#   "visitOrders": [],
#   "user": "61eea2256e0dcf8c5abf729b",
#   "isSold": false,
#   "price": 950000,
#   "category": "TWO_START",
#   "address": "123 Fake St",
#   "email": "hotel-falso2@gmail.com",
#   "description": "hotel 2 description",
#   "name": "Hotel 2",
#   "_id": "61f1664ab8e600a93c826739",
#   "createdAt": "2022-01-26T15:18:34.593Z",
#   "updatedAt": "2022-01-26T15:18:34.593Z",
#   "__v": 0
# }


###
GET http://localhost:4000/hotels

### RESPONSE
# [
#   {
#     "_id": "61f165efc0cba1b25a287c4e",
#     "visitOrders": [],
#     "user": "61eea2256e0dcf8c5abf729b",
#     "isSold": false,
#     "price": 1750000,
#     "category": "FIVE_START",
#     "address": "123 Fake St",
#     "email": "hotel-fake@mail.com",
#     "description": "hotel 1 description",
#     "name": "Hotel 1",
#     "createdAt": "2022-01-26T15:17:03.184Z",
#     "updatedAt": "2022-01-26T15:17:03.184Z",
#     "__v": 0
#   },
#   {
#     "_id": "61f1664ab8e600a93c826739",
#     "visitOrders": [],
#     "user": "61eea2256e0dcf8c5abf729b",
#     "isSold": false,
#     "price": 950000,
#     "category": "TWO_START",
#     "address": "123 Fake St",
#     "email": "hotel-falso2@gmail.com",
#     "description": "hotel 2 description",
#     "name": "Hotel 2",
#     "createdAt": "2022-01-26T15:18:34.593Z",
#     "updatedAt": "2022-01-26T15:18:34.593Z",
#     "__v": 0
#   }
# ]

### ADD ONE HOTEL TO USER FAVORITES
# POST => users/add-favorite/:idHotel
POST http://localhost:4000/users/add-favorite/61f165efc0cba1b25a287c4e
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZjJhN2I4NDU2NGM1MzVjYTJkN2ZhMCIsImlhdCI6MTY0MzI5MjY3OSwiZXhwIjoxNjQzMzc5MDc5fQ.oGtnhCiK_5WSpO7w8XU0uJg5rUdiKUwEX3pVI86-t5A

# RESPONSE

# {
#   "added": {
#     "_id": "61f1664ab8e600a93c826739",
#     "visitOrders": [],
#     "user": "61eea2256e0dcf8c5abf729b",
#     "isSold": false,
#     "price": 950000,
#     "category": "TWO_START",
#     "address": "123 Fake St",
#     "email": "hotel-falso2@gmail.com",
#     "description": "hotel 2 description",
#     "name": "Hotel 2",
#     "createdAt": "2022-01-26T15:18:34.593Z",
#     "updatedAt": "2022-01-26T15:18:34.593Z",
#     "__v": 0
#   }
# }

### get user favorites
# GET => users/favorites
GET http://localhost:4000/users/favorites
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZWVhMjI1NmUwZGNmOGM1YWJmNzI5YiIsImlhdCI6MTY0MzIxMDAzOCwiZXhwIjoxNjQzMjk2NDM4fQ.0hAIBFLeOpJPHe9aLG83iINaap7wUiThU6_WnoRSs5M

# RESPONSE

# {
#   "_id": "61eea2256e0dcf8c5abf729b",
#   "role": "SELLER",
#   "email": "user1@gmail.com",
#   "name": "user1",
#   "__v": 5,
#   "favorites": [
#     {
#       "_id": "61f1664ab8e600a93c826739",
#       "visitOrders": [],
#       "user": "61eea2256e0dcf8c5abf729b",
#       "isSold": false,
#       "price": 950000,
#       "category": "TWO_START",
#       "address": "123 Fake St",
#       "email": "hotel-falso2@gmail.com",
#       "description": "hotel 2 description",
#       "name": "Hotel 2",
#       "createdAt": "2022-01-26T15:18:34.593Z",
#       "updatedAt": "2022-01-26T15:18:34.593Z",
#       "__v": 0
#     },
#     {
#       "_id": "61f165efc0cba1b25a287c4e",
#       "visitOrders": [],
#       "user": "61eea2256e0dcf8c5abf729b",
#       "isSold": false,
#       "price": 1750000,
#       "category": "FIVE_START",
#       "address": "123 Fake St",
#       "email": "hotel-fake@mail.com",
#       "description": "hotel 1 description",
#       "name": "Hotel 1",
#       "createdAt": "2022-01-26T15:17:03.184Z",
#       "updatedAt": "2022-01-26T15:17:03.184Z",
#       "__v": 0
#     }
#   ],
#   "hotelPurchases": []
# }

### DELETE ONE HOTEL FROM USER FAVORITES

DELETE http://localhost:4000/users/delete-favorite/61eea6c8b33e265e3b964233
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZWVhMjI1NmUwZGNmOGM1YWJmNzI5YiIsImlhdCI6MTY0MzA2NTg0NSwiZXhwIjoxNjQzMTUyMjQ1fQ.xUXTscSrAzvswNTwwFbBa3CaPRwN_0njQkUzrP08gO0

# RESPONSE

# {
#   "removed": {
#     "_id": "61eea58154e050bb22907771",
#     "visitOrders": [],
#     "user": "61eea2256e0dcf8c5abf729b",
#     "category": "FIVE_START",
#     "address": "123 Fake St",
#     "email": "hotel-fake@mail.com",
#     "description": "hotel 1 description",
#     "name": "Hotel 1",
#     "createdAt": "2022-01-24T13:11:29.514Z",
#     "updatedAt": "2022-01-24T13:11:29.514Z",
#     "__v": 0
#   }
# }


### PURCHASE ONE HOTEL
#POST => users/purchase/:idHotel
POST http://localhost:4000/users/purchase-hotel/61f2a7574564c535ca2d7f9a
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZjJhN2I4NDU2NGM1MzVjYTJkN2ZhMCIsImlhdCI6MTY0MzI5MjY3OSwiZXhwIjoxNjQzMzc5MDc5fQ.oGtnhCiK_5WSpO7w8XU0uJg5rUdiKUwEX3pVI86-t5A

# RESPONSE
# {
#   "purchased": {
#     "_id": "61f1664ab8e600a93c826739",
#     "visitOrders": [],
#     "user": "61eea2256e0dcf8c5abf729b",
#     "isSold": false,
#     "price": 950000,
#     "category": "TWO_START",
#     "address": "123 Fake St",
#     "email": "hotel-falso2@gmail.com",
#     "description": "hotel 2 description",
#     "name": "Hotel 2",
#     "createdAt": "2022-01-26T15:18:34.593Z",
#     "updatedAt": "2022-01-26T15:18:34.593Z",
#     "__v": 0
#   }
# }

### GET USER PURCHASES
#GET => users/purchases
GET http://localhost:4000/users/purchases
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZjJhN2I4NDU2NGM1MzVjYTJkN2ZhMCIsImlhdCI6MTY0MzI5MjY3OSwiZXhwIjoxNjQzMzc5MDc5fQ.oGtnhCiK_5WSpO7w8XU0uJg5rUdiKUwEX3pVI86-t5A

# {
#   "_id": "61eefb464a0d7647d8704185",
#   "favorites": [],
#   "role": "SELLER",
#   "email": "parkcarlosseb@gmail.com",
#   "name": "carlos park",
#   "__v": 1,
#   "hotelPurchases": [
#     {
#       "_id": "61f1664ab8e600a93c826739",
#       "visitOrders": [],
#       "user": "61eea2256e0dcf8c5abf729b",
#       "isSold": true,
#       "price": 950000,
#       "category": "TWO_START",
#       "address": "123 Fake St",
#       "email": "hotel-falso2@gmail.com",
#       "description": "hotel 2 description",
#       "name": "Hotel 2",
#       "createdAt": "2022-01-26T15:18:34.593Z",
#       "updatedAt": "2022-01-26T15:30:32.706Z",
#       "__v": 0
#     }
#   ]
# }